name: hpack-convert
version: '1.0.1'
synopsis: Convert Cabal manifests into hpack's package.yamls
maintainer: Pedro Tacla Yamada <tacla.yamada@gmail.com>
license: MIT
github: yamadapc/hpack-convert
category: Development

ghc-options: -Wall -fcontext-stack=100
extra-source-files:
  - ./test/data/**/*

dependencies:
  - base
  - base-compat
  - Cabal
  - pretty
  - deepseq
  - directory
  - filepath
  - Glob
  - text
  - containers
  - unordered-containers
  - yaml
  - bytestring
  - vector
  - aeson
  - split

library:
  source-dirs: src
  exposed-modules:
    - Hpack.Convert

executables:
  hpack-convert:
    main: Main.hs
    source-dirs:
      - driver
      - src

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - temporary
      - mockery >= 0.3
      - interpolate
      - aeson-qq
