name: hpack-convert
version: '0.14.2'

synopsis: Convert Cabal manifests into hpack's package.yamls
maintainer: Pedro Tacla Yamada <tacla.yamada@gmail.com>
license: MIT
github: yamadapc/hpack-convert
category: Development

ghc-options: -Wall -fcontext-stack=100

dependencies:
  - base >= 4.7 && < 5
  - base-compat >= 0.8
  - Cabal
  - pretty
  - deepseq
  - directory
  - filepath
  - Glob
  - text
  - containers
  - unordered-containers >= 0.2.7.1
  - yaml
  - bytestring
  - vector
  - aeson == 0.11.*

library:
  source-dirs: src
  dependencies:
  exposed-modules:
    - Hpack
    - Hpack.Convert
    - Hpack.Config
    - Hpack.Run
    - Hpack.Yaml

executables:
  hpack-convert:
    main: Main.hs
    source-dirs: driver
    dependencies:
      - hpack-convert

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - temporary
      - mockery >= 0.3
      - interpolate
      - aeson == 0.11.*
